### ISSUE TITLE
Interest and possible partnership about NOMAD article

### ISSUE THREAD

**Issue by ggnery** [mohammed-nurulhoque/r55#1]
Hello, 
I've been reading the article "Nomad: Cross-Platform Computational Ofﬂoading
and Migration in Femtoclouds Using WebAssembly" and I would like to reproduce the experiments done by you. Today, I am searching  webassembly offloading, and your article is exactly what I am looking for. Are you still updating this project? Can I have access to nomad source code? If yes, could we keep in touch about this?
Best regards,
Gabriel Nery

**Comment by mohammed-nurulhoque** [comment]
Hi @ggnery , sorry for this late reply. I did Nomad in a previous role and I no longer have access to that code.
